name: Release

permissions:
  contents: write

on:
  push:
    tags: [ 'v*.*.*' ]
  

jobs:
  build-and-package:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-mock pyinstaller Pillow
    
    - name: Run unit tests with coverage
      run: |
        pytest --cov=. --cov-report=xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Bundle executable with pyinstaller (Windows)
      if: runner.os == 'Windows'
      run: |
        pyinstaller --onefile --windowed --icon=src/assets/logo.ico --add-data "src/assets/logo.ico;assets" --name AuroraParser --paths src src/main.py

    - name: Bundle executable with pyinstaller (Linux)
      if: runner.os == 'Linux'
      run: |
        pyinstaller --onefile --windowed --icon=src/assets/logo.ico --add-data "src/assets/logo.ico:assets" --name AuroraParser --paths src src/main.py

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: packaged-app-${{ runner.os }}
        path: dist/*
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
